language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=master
  - PHPCS=1

before_script:
  - sh -c "if [ '$PHPCS' != '1' ]; then git clone --depth 1 --branch $CAKE_VERSION git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp; fi"
  - sh -c "if [ '$PHPCS' != '1' ]; then cd ../cakephp; cp -R ../cakephp-mollie plugins/Mollie; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear channel-discover pear.cakephp.org; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear install --alldeps cakephp/CakePHP_CodeSniffer; fi"
  - phpenv rehash

script:
  - sh -c "if [ '$PHPCS' = '1' ]; then phpcs -p --extensions=php --standard=CakePHP .; else cd ../cakephp/app && ../lib/Cake/Console/cake test Mollie Controller/Component/MollieComponent --stderr; fi"

notifications:
  email: false

#  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
#  - echo "<?php
#    class DATABASE_CONFIG {
#    public \$test = array(
#      'datasource' => 'Database/Mysql',
#      'database' => 'cakephp_test',
#      'host' => '0.0.0.0',
#      'login' => 'travis',
#      'persistent' => false,
#    );
#    }" > app/Config/database.php
